/**
 * 错误码和错误信息常量
 */
/**
 * 错误码枚举
 */
export declare enum ErrorCode {
    CONFIG_NOT_FOUND = "E1001",
    CONFIG_PARSE_ERROR = "E1002",
    CONFIG_VALIDATION_ERROR = "E1003",
    CONFIG_MERGE_ERROR = "E1004",
    CONFIG_TRANSFORM_ERROR = "E1005",
    BUILD_FAILED = "E2001",
    BUILD_TIMEOUT = "E2002",
    BUILD_CANCELLED = "E2003",
    BUILD_OUT_OF_MEMORY = "E2004",
    BUILD_DEPENDENCY_ERROR = "E2005",
    ADAPTER_NOT_FOUND = "E3001",
    ADAPTER_INIT_ERROR = "E3002",
    ADAPTER_NOT_AVAILABLE = "E3003",
    ADAPTER_VERSION_MISMATCH = "E3004",
    ADAPTER_CONFIG_ERROR = "E3005",
    PLUGIN_NOT_FOUND = "E4001",
    PLUGIN_LOAD_ERROR = "E4002",
    PLUGIN_INIT_ERROR = "E4003",
    PLUGIN_EXECUTION_ERROR = "E4004",
    PLUGIN_DEPENDENCY_ERROR = "E4005",
    FILE_NOT_FOUND = "E5001",
    FILE_READ_ERROR = "E5002",
    FILE_WRITE_ERROR = "E5003",
    DIRECTORY_NOT_FOUND = "E5004",
    PERMISSION_DENIED = "E5005",
    DEPENDENCY_NOT_FOUND = "E6001",
    DEPENDENCY_VERSION_CONFLICT = "E6002",
    DEPENDENCY_INSTALL_ERROR = "E6003",
    DEPENDENCY_RESOLUTION_ERROR = "E6004",
    NETWORK_ERROR = "E7001",
    DOWNLOAD_ERROR = "E7002",
    UPLOAD_ERROR = "E7003",
    TIMEOUT_ERROR = "E7004",
    SYSTEM_ERROR = "E8001",
    PLATFORM_NOT_SUPPORTED = "E8002",
    NODE_VERSION_MISMATCH = "E8003",
    INSUFFICIENT_RESOURCES = "E8004",
    INVALID_INPUT = "E9001",
    INVALID_OPTION = "E9002",
    INVALID_PATH = "E9003",
    INVALID_FORMAT = "E9004",
    MISSING_REQUIRED_OPTION = "E9005"
}
/**
 * 错误信息映射
 */
export declare const ERROR_MESSAGES: Record<ErrorCode, string>;
/**
 * 错误建议映射
 */
export declare const ERROR_SUGGESTIONS: Record<ErrorCode, string>;
/**
 * 错误分类
 */
export declare const ERROR_CATEGORIES: {
    readonly CONFIGURATION: readonly [ErrorCode.CONFIG_NOT_FOUND, ErrorCode.CONFIG_PARSE_ERROR, ErrorCode.CONFIG_VALIDATION_ERROR, ErrorCode.CONFIG_MERGE_ERROR, ErrorCode.CONFIG_TRANSFORM_ERROR];
    readonly BUILD: readonly [ErrorCode.BUILD_FAILED, ErrorCode.BUILD_TIMEOUT, ErrorCode.BUILD_CANCELLED, ErrorCode.BUILD_OUT_OF_MEMORY, ErrorCode.BUILD_DEPENDENCY_ERROR];
    readonly ADAPTER: readonly [ErrorCode.ADAPTER_NOT_FOUND, ErrorCode.ADAPTER_INIT_ERROR, ErrorCode.ADAPTER_NOT_AVAILABLE, ErrorCode.ADAPTER_VERSION_MISMATCH, ErrorCode.ADAPTER_CONFIG_ERROR];
    readonly PLUGIN: readonly [ErrorCode.PLUGIN_NOT_FOUND, ErrorCode.PLUGIN_LOAD_ERROR, ErrorCode.PLUGIN_INIT_ERROR, ErrorCode.PLUGIN_EXECUTION_ERROR, ErrorCode.PLUGIN_DEPENDENCY_ERROR];
    readonly FILESYSTEM: readonly [ErrorCode.FILE_NOT_FOUND, ErrorCode.FILE_READ_ERROR, ErrorCode.FILE_WRITE_ERROR, ErrorCode.DIRECTORY_NOT_FOUND, ErrorCode.PERMISSION_DENIED];
    readonly DEPENDENCY: readonly [ErrorCode.DEPENDENCY_NOT_FOUND, ErrorCode.DEPENDENCY_VERSION_CONFLICT, ErrorCode.DEPENDENCY_INSTALL_ERROR, ErrorCode.DEPENDENCY_RESOLUTION_ERROR];
    readonly NETWORK: readonly [ErrorCode.NETWORK_ERROR, ErrorCode.DOWNLOAD_ERROR, ErrorCode.UPLOAD_ERROR, ErrorCode.TIMEOUT_ERROR];
    readonly SYSTEM: readonly [ErrorCode.SYSTEM_ERROR, ErrorCode.PLATFORM_NOT_SUPPORTED, ErrorCode.NODE_VERSION_MISMATCH, ErrorCode.INSUFFICIENT_RESOURCES];
    readonly USER_INPUT: readonly [ErrorCode.INVALID_INPUT, ErrorCode.INVALID_OPTION, ErrorCode.INVALID_PATH, ErrorCode.INVALID_FORMAT, ErrorCode.MISSING_REQUIRED_OPTION];
};
/**
 * 错误严重程度
 */
export declare const ERROR_SEVERITY: {
    readonly E1001: "high";
    readonly E1002: "high";
    readonly E1003: "medium";
    readonly E2001: "high";
    readonly E2002: "medium";
    readonly E3001: "high";
    readonly E4001: "medium";
    readonly E5001: "medium";
    readonly E6001: "high";
    readonly E7001: "low";
    readonly E8001: "high";
    readonly E9001: "low";
};
